### ISSUE TITLE
Optional fields disallowed in Proto3

### ISSUE THREAD

**Issue by andy-thomason** [ledgerwatch/interfaces#128]
I have build failures when using the default debian protoc (3.6.1.3) on focal.

```
ii  protobuf-compiler 3.6.1.3-2ubuntu5 amd64        compiler for protocol buffer definition files
```

Build error example:
```
web3/common.proto:35:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
```

It seems that from 3.15 the optional keyword is allowed, but you may need to add special instructions on how to get a more up-to-date
protoc in order to use this.

https://stackoverflow.com/questions/42622015/how-to-define-an-optional-field-in-protobuf-3

If indeed, `optional` is optional, it might be worth removing them.

Feel free to ignore this as it is just a use experience issue.

**Comment by andy-thomason** [comment]
I've added a PR #129 to fix this.

Please verify that it works for you, too.

**Comment by vorot93** [comment]
Fixed in master.
