### ISSUE TITLE
sentry.proto: extend PeerEvents to not miss events

### ISSUE THREAD

**Issue by battlmonstr** [ledgerwatch/interfaces#168]
With the current `PeerEvents`, a naive implementation might miss some events,
and lose track of peers, e.g. in silkworm (pseudocode):

```
count = PeerCount()
// <-- here a new peer connects to sentry after PeerCount call and before PeerEvents call
PeerEvents(OnPeerEvent)
func OnPeerEvent(id) { if (id == Connect) count++ else count-- }
```

An event is lost if it happens between the rpc calls, and the state goes out of sync.

Same issue arises if `Peers()` is called before `PeerEvents()` and we try to maintain a list of peer ids.

### Proposal

Add new fields:

```
message PeerEventsRequest {
    from_timestamp = 1;
}
message PeerCountReply {
    ...
    timestamp = 3;
}
message PeersReply {
    ...
    timestamp = 2;
}
```

Then this would work:

```
count, timestamp = PeerCount()
PeerEvents(timestamp, OnPeerEvent)
```

The sentry has to maintain a little buffer of past events for this to work.

**Comment by AskAlexSharov** [comment]
Maybe better make events idempotent? Then re-order of events or missing them will not cause problems?

**Comment by battlmonstr** [comment]
@AskAlexSharov
What do you mean by "make events idempotent"?

Given that PeerEvents reports the sentry state updates, we lack a baseline for that state.
Consider this scenario:

1. sentry has 0 peers
1. node calls PeerCount and receives count = 0
1. a peer connects to sentry, sentry has 1 peer
1. node subscribes to PeerEvents
1. a peer connects to sentry, sentry has 2 peers
1. node receives a "peer connected" event, and updates count += 1

At the end node peer count = 1, but sentry peer count = 2.

**Comment by AskAlexSharov** [comment]
We wan’t to handle 3 problems: 
1. Event-miss 2. Handling same event twice must be safe

In your scenario idempotent event will look like:
EventType=Connected
TotalPeersCount=2

in this case doesn’t matter: 1. did we miss previous event or not 2. Did we handle same event once or twice.

3. Drop older events if they delivered out-of-order.  Can handle by adding Timestamp or auto-increment EventID. I like EventID more than timestamp - because it doesn’t depend on server clocks, timezones, doesn’t require “monotonic time” language feature, cheaper, smaller, etc… But i can’t find any existing guide about it, like: https://cloud.google.com/apis/design/design_patterns

**Comment by battlmonstr** [comment]
@AskAlexSharov could you explain in which case 2&3 happens for you? I believe that GRPC guarantees no duplicates and order.

Note that both `from_timestamp` and `timestamp` would both be the server time in UTC. I proposed timestamps, because I felt it is simple and good enough, but I see your concern about non-monotonic clocks. So changing it to a monotonic auto-increment ID or version is fine. For example, the telegram bot API is using a similar thing - "update ID".

Adding `TotalPeersCount` solves the count tracking case, but it doesn't solve the peer info tracking case, and I'd like to solve both. Here's the tracking logic we have:

```
peers = Peers()
// <-- here a new peer connects to sentry after PeerCount call and before PeerEvents call
PeerEvents(OnPeerEvent)
func OnPeerEvent(id, peer_id) {
    peer = PeerById(peer_id)
    if (id == Connect) peers.Add(peer) else peers.Remove(peer)
}
```

**Comment by AskAlexSharov** [comment]
@battlmonstr i don’t know - never happens for me. Just responding to your issue. 

“peer info tracking case” - can make it also idempotent. Also can stop storing this info on client side.

**Comment by battlmonstr** [comment]
@AskAlexSharov so your suggestion is to either add a full peers list with each event, or to not change the API, and just call Peers() to get the full list at the time of event arrival, instead of tracking this incrementally, correct?

This is fine for Silkworm. In fact, it is currently not doing anything serious with this info besides logging. Let me check how Erigon uses this PeerEvents API, and reply.

**Comment by AskAlexSharov** [comment]
“ full peers list” - yes. Can add peersID list. We know it’s < 1K.
